Update terraform.yml

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -39,3 +39,10 @@ jobs:
         run: |
           terraform apply -auto-approve tfplan || (echo "Failed to apply Terraform changes"; exit 1)
         working-directory: ./terraform
+      - name: Terraform Apply
+        if: github.ref == 'refs/heads/main'
+        run: |
+         set -x
+          terraform apply -auto-approve tfplan || (echo "Failed to apply Terraform changes"; exit 1)
+        working-directory: ./terraform
+
